spring:
  main:
    banner-mode: log
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${database_host}
    username: ${database_username}
    password: ${database_password}
  thymeleaf:
#    prefix: classpath:templates/
#    suffix: .html
    cache: false
  #dev-tools
  devtools:
    livereload:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

# Log Configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%-5p} ${PID} --- [%15.15t] %-40.40logger{39} :%06L : %m%n"
  level:
    root: info
    web: debug
    com.malgn: debug


#p6spy query logging
decorator:
  datasource:
    p6spy:
      enable-logging: on

#Server Port
server:
  port: 8888

file:
  connect:
    path: ${file_connect_path}
  load:
    path: ${file_load_path}
  upload:
    path: ${file_upload_path}